import { RiskAssessment, RAMS, Chemical, SDS } from './types';

// Helper
const daysFromNow = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().split('T')[0];
};

// ── Risk Assessments ──────────────────────────────────────────────────────────

export const MOCK_RISK_ASSESSMENTS: RiskAssessment[] = [
  {
    id: 'ra-001',
    title: 'General Office Cleaning Risk Assessment',
    taskType: 'Routine Cleaning',
    riskLevel: 'Low',
    createdBy: 'Patricia Nwachukwu',
    lastReviewDate: '2024-01-15',
    nextReviewDate: daysFromNow(200),
    approvalStatus: 'approved',
    approvedBy: 'Richard Hammond',
    approvalDate: '2024-01-20',
    taskDescription: 'Routine cleaning of office areas including desks, floors, toilets, and communal spaces using standard cleaning products.',
    equipmentUsed: ['Mop & bucket', 'Vacuum cleaner', 'Microfibre cloths', 'Spray bottles', 'Wet floor signs'],
    workArea: 'Office floors, reception, toilets, breakout areas',
    requiredPPE: ['Gloves', 'Safety shoes', 'Apron'],
    hazards: [
      {
        hazard: 'Slips & trips on wet floors',
        harm: 'Fractures, sprains, head injury',
        control: 'Use wet floor signs immediately. Mop in sections. Wear non-slip safety shoes.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Chemical skin irritation',
        harm: 'Dermatitis, chemical burns',
        control: 'Wear nitrile gloves. Follow COSHH assessments. Never mix chemicals.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Manual handling — lifting equipment',
        harm: 'Back injury, muscle strain',
        control: 'Use trolleys for heavy items. Team lift when >10kg. Training mandatory.',
        residualRisk: 'Low',
      },
    ],
  },
  {
    id: 'ra-002',
    title: 'Healthcare Facility Deep Clean',
    taskType: 'Deep Clean',
    riskLevel: 'High',
    createdBy: 'Tom Briggs',
    lastReviewDate: '2024-02-01',
    nextReviewDate: daysFromNow(18),
    approvalStatus: 'approved',
    approvedBy: 'Patricia Nwachukwu',
    approvalDate: '2024-02-05',
    taskDescription: 'Full deep clean of healthcare ward including clinical areas, isolation rooms and high-touch surfaces using hospital-grade disinfectants.',
    equipmentUsed: ['Steam cleaner', 'HEPA vacuum', 'UV-C disinfection unit', 'Colour-coded cloths', 'Biohazard bags'],
    workArea: 'Hospital ward, isolation rooms, nurses station, patient bathrooms',
    requiredPPE: ['Gloves', 'Eye protection', 'Mask', 'Apron', 'Safety shoes'],
    hazards: [
      {
        hazard: 'Biological contamination / infection risk',
        harm: 'Serious infection, cross-contamination',
        control: 'Full PPE at all times. Double-bag clinical waste. Sanitise hands frequently. IPC training required.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Chemical exposure — strong disinfectants',
        harm: 'Respiratory irritation, chemical burns',
        control: 'Wear FFP2 mask and eye protection. Ensure adequate ventilation. Follow dilution ratios exactly.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Needlestick / sharps injury',
        harm: 'Bloodborne infection (HIV, Hepatitis B/C)',
        control: 'Never recap needles. Use sharps bin. Follow NHS sharps protocol. Report all incidents immediately.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Electrical equipment near water',
        harm: 'Electric shock, cardiac arrest',
        control: 'Check all electrical equipment before use. Do not use near standing water. PAT tested equipment only.',
        residualRisk: 'Low',
      },
    ],
  },
  {
    id: 'ra-003',
    title: 'External Window & Facade Cleaning',
    taskType: 'Window Cleaning',
    riskLevel: 'High',
    createdBy: 'Richard Hammond',
    lastReviewDate: '2024-03-10',
    nextReviewDate: daysFromNow(-5),
    approvalStatus: 'pending',
    taskDescription: 'Water-fed pole and rope access window cleaning for external building facades above 2 metres.',
    equipmentUsed: ['Water-fed pole system', 'Safety harness', 'Anchor points', 'Rope access kit', 'MEWP'],
    workArea: 'Building exterior, rooftop anchor points, scaffolding',
    requiredPPE: ['Safety harness', 'Hi-vis vest', 'Safety shoes', 'Gloves', 'Hard hat'],
    hazards: [
      {
        hazard: 'Working at height — fall risk',
        harm: 'Fatal injury, serious fractures',
        control: 'Full harness and lanyard anchored to rated points. Rescue plan in place. 2-person rule enforced. PASMA/IPAF trained only.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Falling objects striking pedestrians',
        harm: 'Head injury, fatality',
        control: 'Exclusion zone below work area. Safety nets where possible. Hard hat mandatory in exclusion zone.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Adverse weather conditions',
        harm: 'Fall from height, hypothermia',
        control: 'Wind speed monitoring. Stop work if >25mph. No work in ice, lightning or heavy rain.',
        residualRisk: 'Low',
      },
    ],
  },
  {
    id: 'ra-004',
    title: 'School Classroom Evening Clean',
    taskType: 'Routine Cleaning',
    riskLevel: 'Low',
    createdBy: 'Amanda Foster',
    lastReviewDate: '2024-01-05',
    nextReviewDate: daysFromNow(290),
    approvalStatus: 'approved',
    approvedBy: 'Tom Briggs',
    approvalDate: '2024-01-08',
    taskDescription: 'Evening routine cleaning of primary school classrooms, corridors and toilet blocks after school hours.',
    equipmentUsed: ['Mop & bucket', 'Vacuum', 'Spray & wipe', 'Bin liners'],
    workArea: 'Classrooms, corridors, toilets, staff room',
    requiredPPE: ['Gloves', 'Safety shoes'],
    hazards: [
      {
        hazard: 'Lone working out-of-hours',
        harm: 'Medical emergency undetected, personal safety risk',
        control: 'Check-in/check-out system. Buddy call system. Emergency contact held by manager.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Slips on polished floor surfaces',
        harm: 'Sprains, fractures',
        control: 'Wet floor signs. Correct mop technique. Non-slip footwear mandatory.',
        residualRisk: 'Low',
      },
    ],
  },
  {
    id: 'ra-005',
    title: 'Industrial Kitchen & Canteen Clean',
    taskType: 'Kitchen Cleaning',
    riskLevel: 'Medium',
    createdBy: 'Tom Briggs',
    lastReviewDate: '2024-04-01',
    nextReviewDate: daysFromNow(25),
    approvalStatus: 'approved',
    approvedBy: 'Patricia Nwachukwu',
    approvalDate: '2024-04-05',
    taskDescription: 'Deep clean of commercial kitchen including extraction fans, grease traps, cooking surfaces and floor drains.',
    equipmentUsed: ['Degreaser spray', 'High-pressure washer', 'Scrubbing pads', 'Drain rods', 'Heat-resistant gloves'],
    workArea: 'Kitchen, canteen, cold store, grease trap area',
    requiredPPE: ['Gloves', 'Eye protection', 'Apron', 'Safety shoes', 'Mask'],
    hazards: [
      {
        hazard: 'Hot surfaces — burns',
        harm: 'Scalds, burns',
        control: 'Allow equipment to cool fully before cleaning. Use heat-resistant gloves. Display "Hot Surface" signs.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Grease buildup — fire risk',
        harm: 'Fire, explosion',
        control: 'Remove all grease from extraction duct. Use non-flammable degreasers. Hot work permit if required.',
        residualRisk: 'Low',
      },
      {
        hazard: 'Strong alkaline degreasers — chemical burns',
        harm: 'Eye injury, skin burns',
        control: 'Wear goggles and nitrile gloves. Eyewash station on-site. Follow COSHH sheet.',
        residualRisk: 'Low',
      },
    ],
  },
  {
    id: 'ra-006',
    title: 'Construction Site Post-Build Clean',
    taskType: 'Post-Construction Clean',
    riskLevel: 'High',
    createdBy: 'Claire Ashton',
    lastReviewDate: daysFromNow(-45),
    nextReviewDate: daysFromNow(-15),
    approvalStatus: 'not_approved',
    taskDescription: 'Final builder\'s clean of new commercial build including removing construction debris, dust, adhesive residues and builder\'s compounds from all surfaces.',
    equipmentUsed: ['Industrial vacuum', 'Razor scrapers', 'Chemical strippers', 'Pressure washer', 'HEPA filter vacuum'],
    workArea: 'All floors, glazing, fixtures, sanitary ware, external areas',
    requiredPPE: ['Gloves', 'Hard hat', 'Eye protection', 'Mask', 'Safety shoes', 'Hi-vis vest'],
    hazards: [
      {
        hazard: 'Construction debris — cuts and punctures',
        harm: 'Lacerations, puncture wounds, tetanus risk',
        control: 'Wear cut-resistant gloves. Steel toe-cap boots mandatory. Clear debris before cleaning.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Silica dust inhalation',
        harm: 'Silicosis, lung disease',
        control: 'FFP3 mask mandatory. Wet suppression where possible. HEPA vacuum only. Limit exposure time.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Chemical strippers — fume inhalation',
        harm: 'Respiratory damage, dizziness',
        control: 'Use only in ventilated areas. Wear full-face respirator. Read COSHH sheets before use.',
        residualRisk: 'Medium',
      },
      {
        hazard: 'Unstable structures / unfinished areas',
        harm: 'Crush injury, fall through floor',
        control: 'Pre-work site survey mandatory. Do not enter unbarriered areas. Site induction required.',
        residualRisk: 'Medium',
      },
    ],
  },
];

// ── RAMS ─────────────────────────────────────────────────────────────────────

export const MOCK_RAMS: RAMS[] = [
  {
    id: 'rams-001',
    siteName: 'St. Mary\'s Hospital — Ward B',
    clientName: 'NHS Trust East',
    description: 'Daily clinical-grade ward clean including isolation rooms and high-touch surface disinfection.',
    workingHours: 'Monday–Friday, 06:00–08:00 & 17:00–19:00',
    status: 'approved',
    lastUpdated: '2024-02-10',
    supervisor: 'Patricia Nwachukwu',
    workMethod: [
      'Sign in at hospital reception and collect visitor badge.',
      'Collect all equipment from the designated cleaning store.',
      'Don full PPE: apron, nitrile gloves, eye protection, FFP2 mask.',
      'Begin with patient bathrooms — use colour-coded red cloths only.',
      'Clean high-touch surfaces (door handles, call buttons, bed rails) with approved hospital disinfectant.',
      'Mop floors using figure-8 technique with 1000ppm chlorine solution.',
      'Replace clinical waste bags and clinical waste bins.',
      'Doff PPE safely — gloves last. Hand hygiene immediately after.',
      'Return all equipment clean and store correctly.',
      'Sign out and report any incidents to ward manager.',
    ],
    emergencyProcedures: [
      'Needlestick: Do not suck wound. Run under water 5 minutes. Report to ward manager immediately. Attend A&E.',
      'Chemical spill: Contain with spill kit. Evacuate immediate area. Inform site manager.',
      'Fire: Activate nearest call point. Evacuate via nearest fire exit. Do not use lift.',
      'Medical emergency: Call 999. Do not move patient. Inform ward staff.',
    ],
    linkedRiskAssessmentIds: ['ra-002'],
    signedCopyAvailable: true,
  },
  {
    id: 'rams-002',
    siteName: 'Meridian Tower — Floors 12-18',
    clientName: 'Meridian Capital Group',
    description: 'Nightly office clean of open-plan office floors including hot desks, meeting rooms and kitchen areas.',
    workingHours: 'Monday–Friday, 19:00–22:00',
    status: 'approved',
    lastUpdated: '2024-03-01',
    supervisor: 'Tom Briggs',
    workMethod: [
      'Collect keys from night security at ground floor reception.',
      'Access service lift with cleaning trolley.',
      'Start on floor 18, work downwards to floor 12.',
      'Empty all bins — general waste and recycling kept separate.',
      'Wipe all desks with multi-surface spray and microfibre cloth.',
      'Clean all meeting rooms: wipe boards, straighten furniture, hoover if required.',
      'Clean kitchen areas: sanitise surfaces, clean appliance exteriors, replace bin liners.',
      'Vacuum all carpeted areas. Mop hard floors.',
      'Lock all rooms and replace keys with night security.',
    ],
    emergencyProcedures: [
      'Fire: Activate nearest alarm. Evacuate via emergency stairwell. Muster at car park.',
      'Injury: Call 999 if serious. First aid kit located at each floor kitchenette.',
      'Security incident: Contact night security immediately on ext. 0.',
    ],
    linkedRiskAssessmentIds: ['ra-001'],
    signedCopyAvailable: true,
  },
  {
    id: 'rams-003',
    siteName: 'Westside Primary School',
    clientName: 'Westside Academy Trust',
    description: 'Evening routine clean of classrooms, corridors and toilet blocks after pupils depart.',
    workingHours: 'Monday–Friday, 16:30–19:30',
    status: 'review_required',
    lastUpdated: '2023-11-15',
    supervisor: 'Amanda Foster',
    workMethod: [
      'Collect master key from school office before 16:30.',
      'Begin with toilet blocks — full sanitisation of all surfaces.',
      'Move to classrooms: empty bins, wipe tables and chairs, tidy resources.',
      'Vacuum carpeted areas in library and staff room.',
      'Mop all hard floor corridors and entrance hall.',
      'Secure all windows and doors in each room before moving on.',
      'Report any damage or graffiti via maintenance log.',
      'Return keys to school office or key safe.',
    ],
    emergencyProcedures: [
      'Fire: Activate alarm. Evacuate immediately. Call 999. Muster on school field.',
      'Lone worker emergency: Call manager. Emergency contact is Amanda Foster: 07XXX XXXXXX.',
      'Suspicious person: Do not approach. Call 999. Exit safely.',
    ],
    linkedRiskAssessmentIds: ['ra-004'],
    signedCopyAvailable: false,
  },
  {
    id: 'rams-004',
    siteName: 'Hartley & Co Headquarters',
    clientName: 'Hartley & Co Solicitors',
    description: 'Weekly deep clean of law firm offices including document rooms, reception and executive suites.',
    workingHours: 'Saturday, 08:00–14:00',
    status: 'approved',
    lastUpdated: '2024-04-15',
    supervisor: 'Richard Hammond',
    workMethod: [
      'Collect access fob from key safe (code provided to supervisor only).',
      'Sign visitor log kept at reception desk.',
      'Do not open, move or discard any documents from desks — treat as confidential.',
      'Vacuum all areas including executive offices.',
      'Deep clean all toilet and bathroom facilities.',
      'Polish reception desk and glass partitions.',
      'Clean kitchen: descale kettle, clean oven exterior, sanitise all surfaces.',
      'Lock all rooms. Secure building and replace fob.',
    ],
    emergencyProcedures: [
      'Fire: Activate alarm. Exit via rear fire escape. Call 999. Muster on street.',
      'Data breach: Do not photograph or remove any documents. Report to manager.',
    ],
    linkedRiskAssessmentIds: ['ra-001'],
    signedCopyAvailable: true,
  },
  {
    id: 'rams-005',
    siteName: 'Greenfield Industrial Unit 7',
    clientName: 'Greenfield Manufacturing',
    description: 'Post-build construction clean of newly completed warehouse unit including concrete dust removal and glazing clean.',
    workingHours: 'Monday–Wednesday, 07:00–17:00',
    status: 'draft',
    lastUpdated: daysFromNow(-2),
    supervisor: 'Claire Ashton',
    workMethod: [
      'Site induction with site manager before works commence.',
      'Don full PPE: hard hat, hi-vis, steel-cap boots, FFP3 mask, goggles, gloves.',
      'Begin with HEPA vacuum of all concrete dust from floors.',
      'Scrape adhesive residues from floor tiles using razor scraper.',
      'Power wash external areas and loading bay.',
      'Clean all glazing inside and out using water-fed system.',
      'Remove all waste and debris to skip — segregate waste streams.',
      'Final walk-through with site manager before sign-off.',
    ],
    emergencyProcedures: [
      'Injury: Call 999. First aid kit in site office. Report to site manager.',
      'Dust emergency / fume exposure: Exit immediately. Fresh air. Call 999 if symptoms persist.',
      'Fire: Activate alarm. Exit via main gate. Muster in car park.',
    ],
    linkedRiskAssessmentIds: ['ra-006'],
    signedCopyAvailable: false,
  },
];

// ── Chemicals (COSHH Register) ────────────────────────────────────────────────

export const MOCK_CHEMICALS: Chemical[] = [
  {
    id: 'chem-001',
    name: 'Jangro Multi-Surface Cleaner',
    manufacturer: 'Jangro Ltd',
    hazardType: 'Irritant',
    hazardSymbols: ['GHS07'],
    storageLocation: 'Chemical store — shelf A1',
    ppeRequired: ['Gloves'],
    sdsAvailable: true,
    sdsId: 'sds-001',
    firstAidMeasures: 'Eye contact: rinse with water 15 minutes. Skin: wash with soap and water. If swallowed: do not induce vomiting, seek medical advice.',
    spillResponse: 'Absorb with paper towels. Dispose to drain with plenty of water. Ventilate area.',
    disposalMethod: 'Diluted product: drain disposal. Empty containers: recycle or general waste.',
    handlingInstructions: 'Dilute 1:10 with water before use. Wear nitrile gloves. Avoid eye contact.',
    maxExposureLimit: 'Not established',
  },
  {
    id: 'chem-002',
    name: 'Dettol Hospital Grade Disinfectant',
    manufacturer: 'Reckitt Benckiser',
    hazardType: 'Corrosive',
    hazardSymbols: ['GHS05', 'GHS07'],
    storageLocation: 'Chemical store — shelf A2 (locked)',
    ppeRequired: ['Gloves', 'Eye protection', 'Apron'],
    sdsAvailable: true,
    sdsId: 'sds-002',
    firstAidMeasures: 'Eyes: flush immediately with water for 15+ minutes. Seek immediate medical attention. Skin: remove contaminated clothing, wash with water.',
    spillResponse: 'Evacuate area. Wear full PPE. Absorb with vermiculite. Place in sealed container. Do not discharge to drain.',
    disposalMethod: 'Hazardous waste contractor only. Label all containers.',
    handlingInstructions: 'Dilute per label. Maximum 1000ppm in clinical areas. Never mix with bleach. Ensure ventilation.',
    maxExposureLimit: '0.5 ppm TWA (chlorine)',
  },
  {
    id: 'chem-003',
    name: 'Evans Vanodine Floor Cleaner',
    manufacturer: 'Evans Vanodine International',
    hazardType: 'Irritant',
    hazardSymbols: ['GHS07'],
    storageLocation: 'Chemical store — shelf B1',
    ppeRequired: ['Gloves', 'Safety shoes'],
    sdsAvailable: true,
    sdsId: 'sds-003',
    firstAidMeasures: 'Skin: wash thoroughly. Eyes: rinse with water. If irritation persists consult a doctor.',
    spillResponse: 'Mop up with absorbent material. Dispose of via drain with water. Ventilate area.',
    disposalMethod: 'Diluted product: drain. Concentrated: waste contractor.',
    handlingInstructions: 'Dilute 1:20 with warm water. Do not use on wood floors. Rinse floor after application in food areas.',
    maxExposureLimit: 'Not established',
  },
  {
    id: 'chem-004',
    name: 'Solvitol Heavy Duty Degreaser',
    manufacturer: 'Holchem Laboratories',
    hazardType: 'Corrosive',
    hazardSymbols: ['GHS05', 'GHS02'],
    storageLocation: 'Chemical store — shelf B2 (locked, flammable cabinet)',
    ppeRequired: ['Gloves', 'Eye protection', 'Apron', 'Mask'],
    sdsAvailable: true,
    sdsId: 'sds-004',
    firstAidMeasures: 'CORROSIVE. Eyes: flush with water 20+ minutes. Seek immediate hospital treatment. Skin: remove clothing, wash with large amounts of water.',
    spillResponse: 'Do NOT allow into drains. Use spill kit. Absorbent granules only. Double-bag and label as hazardous.',
    disposalMethod: 'Registered hazardous waste contractor. Provide SDS to contractor.',
    handlingInstructions: 'Use only in ventilated areas. Wear RPE (half-face respirator) if ventilation inadequate. Never mix with acids.',
    maxExposureLimit: '0.05 mg/m³ (sodium hydroxide)',
  },
  {
    id: 'chem-005',
    name: 'Actichlor Plus Chlorine Tablets',
    manufacturer: 'Ecolab Ltd',
    hazardType: 'Oxidising',
    hazardSymbols: ['GHS03', 'GHS07', 'GHS09'],
    storageLocation: 'Chemical store — shelf C1 (separate from flammables)',
    ppeRequired: ['Gloves', 'Eye protection', 'Mask'],
    sdsAvailable: false,
    firstAidMeasures: 'Eyes: immediate irrigation 15 minutes. Inhalation: fresh air, rest. Seek medical attention if symptoms persist.',
    spillResponse: 'Sweep up tablets — do not use water. Place in sealed dry container. Dispose via hazardous waste.',
    disposalMethod: 'Do not dissolve unused tablets in drain. Contact waste contractor.',
    handlingInstructions: 'Dissolve one tablet per litre of cold water (NOT hot). Wear mask when dissolving. Do not mix with any other chemicals.',
    maxExposureLimit: '0.5 ppm STEL (chlorine gas)',
  },
  {
    id: 'chem-006',
    name: 'Prochem Tile & Grout Cleaner',
    manufacturer: 'Prochem Europe Ltd',
    hazardType: 'Irritant',
    hazardSymbols: ['GHS07'],
    storageLocation: 'Chemical store — shelf A3',
    ppeRequired: ['Gloves', 'Eye protection'],
    sdsAvailable: true,
    sdsId: 'sds-006',
    firstAidMeasures: 'Skin: rinse with water. Eyes: rinse with water 10 minutes. Consult doctor if irritation continues.',
    spillResponse: 'Mop up with absorbent. Rinse area with water. Ventilate.',
    disposalMethod: 'Diluted: drain disposal. Concentrated: environmental regulations apply.',
    handlingInstructions: 'Dilute 1:5 with water. Apply with brush, leave 5 minutes, agitate and rinse.',
    maxExposureLimit: 'Not established',
  },
  {
    id: 'chem-007',
    name: 'P3-Alcodes IPA Disinfectant 70%',
    manufacturer: 'Ecolab Professional',
    hazardType: 'Flammable',
    hazardSymbols: ['GHS02', 'GHS07'],
    storageLocation: 'Chemical store — flammable cabinet (max 50L)',
    ppeRequired: ['Gloves', 'Eye protection'],
    sdsAvailable: true,
    sdsId: 'sds-007',
    firstAidMeasures: 'Inhalation of vapour: fresh air, rest. Skin: wash thoroughly. Eyes: rinse with water.',
    spillResponse: 'Eliminate all ignition sources immediately. Absorb with dry sand. Dispose as flammable waste.',
    disposalMethod: 'Flammable liquid waste contractor only.',
    handlingInstructions: 'Highly flammable. Keep away from heat and ignition sources. No smoking. Flash point 12°C.',
    maxExposureLimit: '400 ppm TWA, 500 ppm STEL (IPA)',
  },
  {
    id: 'chem-008',
    name: 'Fabuloso Multi-Purpose Cleaner',
    manufacturer: 'Colgate-Palmolive',
    hazardType: 'Low Hazard',
    hazardSymbols: [],
    storageLocation: 'Chemical store — shelf A4',
    ppeRequired: ['Gloves'],
    sdsAvailable: false,
    firstAidMeasures: 'Skin: rinse with water. Eyes: rinse with water. If swallowed: drink water, do not induce vomiting.',
    spillResponse: 'Mop up, rinse area with water.',
    disposalMethod: 'Drain disposal acceptable when diluted.',
    handlingInstructions: 'Ready to use. Do not mix with bleach or other chemicals. Avoid eye contact.',
  },
];

// ── SDS Library ───────────────────────────────────────────────────────────────

export const MOCK_SDS: SDS[] = [
  {
    id: 'sds-001',
    chemicalId: 'chem-001',
    chemicalName: 'Jangro Multi-Surface Cleaner',
    issueDate: '2023-06-01',
    reviewDate: daysFromNow(120),
    status: 'valid',
    manufacturer: 'Jangro Ltd',
    fileName: 'Jangro-Multi-Surface-SDS-v3.pdf',
    fileSize: '0.8 MB',
    revision: 'Rev. 3',
  },
  {
    id: 'sds-002',
    chemicalId: 'chem-002',
    chemicalName: 'Dettol Hospital Grade Disinfectant',
    issueDate: '2023-09-15',
    reviewDate: daysFromNow(8),
    status: 'review_soon',
    manufacturer: 'Reckitt Benckiser',
    fileName: 'Dettol-HospGrade-SDS.pdf',
    fileSize: '1.2 MB',
    revision: 'Rev. 7',
  },
  {
    id: 'sds-003',
    chemicalId: 'chem-003',
    chemicalName: 'Evans Vanodine Floor Cleaner',
    issueDate: '2022-12-01',
    reviewDate: daysFromNow(-25),
    status: 'expired',
    manufacturer: 'Evans Vanodine International',
    fileName: 'Evans-Floor-Cleaner-SDS.pdf',
    fileSize: '0.6 MB',
    revision: 'Rev. 2',
  },
  {
    id: 'sds-004',
    chemicalId: 'chem-004',
    chemicalName: 'Solvitol Heavy Duty Degreaser',
    issueDate: '2023-11-01',
    reviewDate: daysFromNow(280),
    status: 'valid',
    manufacturer: 'Holchem Laboratories',
    fileName: 'Solvitol-HeavyDuty-SDS.pdf',
    fileSize: '1.5 MB',
    revision: 'Rev. 4',
  },
  {
    id: 'sds-005',
    chemicalId: 'chem-005',
    chemicalName: 'Actichlor Plus Chlorine Tablets',
    issueDate: '2022-06-01',
    reviewDate: daysFromNow(-60),
    status: 'expired',
    manufacturer: 'Ecolab Ltd',
    revision: 'Rev. 1',
  },
  {
    id: 'sds-006',
    chemicalId: 'chem-006',
    chemicalName: 'Prochem Tile & Grout Cleaner',
    issueDate: '2024-01-10',
    reviewDate: daysFromNow(340),
    status: 'valid',
    manufacturer: 'Prochem Europe Ltd',
    fileName: 'Prochem-TileGrout-SDS.pdf',
    fileSize: '0.7 MB',
    revision: 'Rev. 2',
  },
  {
    id: 'sds-007',
    chemicalId: 'chem-007',
    chemicalName: 'P3-Alcodes IPA Disinfectant 70%',
    issueDate: '2023-08-01',
    reviewDate: daysFromNow(160),
    status: 'valid',
    manufacturer: 'Ecolab Professional',
    fileName: 'P3-Alcodes-IPA-SDS.pdf',
    fileSize: '1.1 MB',
    revision: 'Rev. 5',
  },
  {
    id: 'sds-008',
    chemicalId: 'chem-008',
    chemicalName: 'Fabuloso Multi-Purpose Cleaner',
    issueDate: '2023-01-01',
    reviewDate: daysFromNow(-10),
    status: 'expired',
    manufacturer: 'Colgate-Palmolive',
    revision: 'Rev. 1',
  },
];

// ── Helpers ───────────────────────────────────────────────────────────────────

export const getRiskById       = (id: string) => MOCK_RISK_ASSESSMENTS.find(r => r.id === id);
export const getRAMSById       = (id: string) => MOCK_RAMS.find(r => r.id === id);
export const getChemicalById   = (id: string) => MOCK_CHEMICALS.find(c => c.id === id);
export const getSDSById        = (id: string) => MOCK_SDS.find(s => s.id === id);
export const getSDSByChemical  = (chemId: string) => MOCK_SDS.find(s => s.chemicalId === chemId);

export const daysUntil = (dateStr: string): number => {
  if (!dateStr) return Infinity;
  const now = new Date(); now.setHours(0, 0, 0, 0);
  return Math.ceil((new Date(dateStr).getTime() - now.getTime()) / 86_400_000);
};
