import { PPEIssueRecord, PPEInventoryRecord, PPEItemType } from '../types';

export const PPE_ITEM_ICONS: Record<PPEItemType, string> = {
  'Safety Gloves':              'back_hand',
  'Safety Shoes':               'hiking',
  'High-Visibility Vest':       'directions_run',
  'Face Mask / Respirator':     'masks',
  'Eye Protection':             'visibility',
  'Apron / Protective Clothing':'dry_cleaning',
};

export const PPE_ITEM_COLORS: Record<PPEItemType, string> = {
  'Safety Gloves':              'bg-blue-100 text-blue-700',
  'Safety Shoes':               'bg-amber-100 text-amber-700',
  'High-Visibility Vest':       'bg-yellow-100 text-yellow-700',
  'Face Mask / Respirator':     'bg-teal-100 text-teal-700',
  'Eye Protection':             'bg-violet-100 text-violet-700',
  'Apron / Protective Clothing':'bg-rose-100 text-rose-700',
};

export const ALL_PPE_TYPES: PPEItemType[] = [
  'Safety Gloves',
  'Safety Shoes',
  'High-Visibility Vest',
  'Face Mask / Respirator',
  'Eye Protection',
  'Apron / Protective Clothing',
];

export const MOCK_PPE_RECORDS: PPEIssueRecord[] = [
  {
    id: 'ppe-001',
    workerName: 'James Thornton',
    workerLocation: 'Manchester North',
    workerInitials: 'JT',
    workerAvatarColor: 'bg-blue-500',
    ppeType: 'Safety Gloves',
    size: 'L',
    issueDate: '2025-08-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-02-01',
    issuedBy: 'Admin',
    notes: 'Issued for chemical handling duties.',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-08-01' },
    status: 'Overdue',
    replacementHistory: [
      { date: '2025-02-01', reason: 'Scheduled 6-month replacement', issuedBy: 'Admin', ppeType: 'Safety Gloves' },
      { date: '2024-08-01', reason: 'Initial issuance', issuedBy: 'Admin', ppeType: 'Safety Gloves' },
    ],
  },
  {
    id: 'ppe-002',
    workerName: 'Sarah Mitchell',
    workerLocation: 'Birmingham Central',
    workerInitials: 'SM',
    workerAvatarColor: 'bg-pink-500',
    ppeType: 'Safety Shoes',
    size: '6',
    issueDate: '2025-01-15',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 12,
    nextReplacementDue: '2026-01-15',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-01-15' },
    status: 'Overdue',
    replacementHistory: [
      { date: '2024-01-15', reason: 'Annual replacement', issuedBy: 'Admin', ppeType: 'Safety Shoes' },
    ],
  },
  {
    id: 'ppe-003',
    workerName: 'David Okafor',
    workerLocation: 'London South',
    workerInitials: 'DO',
    workerAvatarColor: 'bg-emerald-500',
    ppeType: 'High-Visibility Vest',
    size: 'M',
    issueDate: '2025-10-15',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-04-15',
    issuedBy: 'Admin',
    notes: 'Required for outdoor site work.',
    acknowledgement: { status: 'Pending' },
    status: 'Valid',
    replacementHistory: [],
  },
  {
    id: 'ppe-004',
    workerName: 'Emma Clarke',
    workerLocation: 'Leeds West',
    workerInitials: 'EC',
    workerAvatarColor: 'bg-violet-500',
    ppeType: 'Face Mask / Respirator',
    size: 'S',
    issueDate: '2025-08-25',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-02-25',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-08-25' },
    status: 'Due Soon',
    replacementHistory: [
      { date: '2025-02-25', reason: 'Scheduled replacement', issuedBy: 'Admin', ppeType: 'Face Mask / Respirator' },
    ],
  },
  {
    id: 'ppe-005',
    workerName: 'Ryan Patel',
    workerLocation: 'Bristol East',
    workerInitials: 'RP',
    workerAvatarColor: 'bg-orange-500',
    ppeType: 'Eye Protection',
    size: 'One Size',
    issueDate: '2025-11-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-05-01',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-11-01' },
    status: 'Valid',
    replacementHistory: [],
  },
  {
    id: 'ppe-006',
    workerName: 'Priya Singh',
    workerLocation: 'Manchester South',
    workerInitials: 'PS',
    workerAvatarColor: 'bg-rose-500',
    ppeType: 'Apron / Protective Clothing',
    size: 'M',
    issueDate: '2024-09-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 12,
    nextReplacementDue: '2025-09-01',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Pending' },
    status: 'Overdue',
    replacementHistory: [
      { date: '2023-09-01', reason: 'Initial issuance', issuedBy: 'Admin', ppeType: 'Apron / Protective Clothing' },
    ],
  },
  {
    id: 'ppe-007',
    workerName: 'Luke Henderson',
    workerLocation: 'Sheffield North',
    workerInitials: 'LH',
    workerAvatarColor: 'bg-sky-500',
    ppeType: 'Safety Gloves',
    size: 'XL',
    issueDate: '2025-09-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-03-01',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-09-01' },
    status: 'Due Soon',
    replacementHistory: [
      { date: '2025-03-01', reason: 'Scheduled 6-month replacement', issuedBy: 'Admin', ppeType: 'Safety Gloves' },
    ],
  },
  {
    id: 'ppe-008',
    workerName: 'Amara Osei',
    workerLocation: 'London East',
    workerInitials: 'AO',
    workerAvatarColor: 'bg-teal-500',
    ppeType: 'Safety Shoes',
    size: '5',
    issueDate: '2025-12-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 12,
    nextReplacementDue: '2026-12-01',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-12-01' },
    status: 'Valid',
    replacementHistory: [],
  },
  {
    id: 'ppe-009',
    workerName: 'Chris Evans',
    workerLocation: 'Nottingham Central',
    workerInitials: 'CE',
    workerAvatarColor: 'bg-indigo-500',
    ppeType: 'High-Visibility Vest',
    size: 'L',
    issueDate: '2025-09-15',
    conditionAtIssue: 'Good',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-09-15',
    issuedBy: 'Admin',
    notes: 'Replacement unit — original was damaged.',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-09-15' },
    status: 'Valid',
    replacementHistory: [
      { date: '2025-09-15', reason: 'Damage replacement', issuedBy: 'Admin', ppeType: 'High-Visibility Vest' },
    ],
  },
  {
    id: 'ppe-010',
    workerName: 'Fatima Hassan',
    workerLocation: 'Liverpool West',
    workerInitials: 'FH',
    workerAvatarColor: 'bg-amber-500',
    ppeType: 'Face Mask / Respirator',
    size: 'M',
    issueDate: '2025-01-01',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2025-07-01',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Pending' },
    status: 'Overdue',
    replacementHistory: [],
  },
  {
    id: 'ppe-011',
    workerName: 'Michael Brown',
    workerLocation: 'Glasgow Central',
    workerInitials: 'MB',
    workerAvatarColor: 'bg-cyan-600',
    ppeType: 'Eye Protection',
    size: 'One Size',
    issueDate: '2025-08-28',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 6,
    nextReplacementDue: '2026-02-28',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-08-28' },
    status: 'Due Soon',
    replacementHistory: [],
  },
  {
    id: 'ppe-012',
    workerName: 'Grace Obi',
    workerLocation: 'Cardiff South',
    workerInitials: 'GO',
    workerAvatarColor: 'bg-lime-600',
    ppeType: 'Apron / Protective Clothing',
    size: 'S',
    issueDate: '2025-11-15',
    conditionAtIssue: 'New',
    replacementPeriodMonths: 12,
    nextReplacementDue: '2026-11-15',
    issuedBy: 'Admin',
    acknowledgement: { status: 'Acknowledged', acknowledgedAt: '2025-11-15' },
    status: 'Valid',
    replacementHistory: [],
  },
];

export const MOCK_PPE_INVENTORY: PPEInventoryRecord[] = [
  {
    id: 'inv-001',
    ppeType: 'Safety Gloves',
    availableQuantity: 48,
    minimumStockLevel: 20,
    lastRestocked: '2026-01-10',
    stockStatus: 'Normal',
    unit: 'pairs',
  },
  {
    id: 'inv-002',
    ppeType: 'Safety Shoes',
    availableQuantity: 8,
    minimumStockLevel: 10,
    lastRestocked: '2025-11-20',
    stockStatus: 'Low Stock',
    unit: 'pairs',
  },
  {
    id: 'inv-003',
    ppeType: 'High-Visibility Vest',
    availableQuantity: 22,
    minimumStockLevel: 15,
    lastRestocked: '2025-12-05',
    stockStatus: 'Normal',
    unit: 'units',
  },
  {
    id: 'inv-004',
    ppeType: 'Face Mask / Respirator',
    availableQuantity: 0,
    minimumStockLevel: 30,
    lastRestocked: '2025-10-01',
    stockStatus: 'Out of Stock',
    unit: 'units',
  },
  {
    id: 'inv-005',
    ppeType: 'Eye Protection',
    availableQuantity: 31,
    minimumStockLevel: 15,
    lastRestocked: '2026-01-22',
    stockStatus: 'Normal',
    unit: 'units',
  },
  {
    id: 'inv-006',
    ppeType: 'Apron / Protective Clothing',
    availableQuantity: 6,
    minimumStockLevel: 10,
    lastRestocked: '2025-09-15',
    stockStatus: 'Low Stock',
    unit: 'units',
  },
];
